<template>
  <div>
    <div class="md-subheading">
      Required quantities and qualities of libraries, cDNA, or other materials, either generated by IGO for a downstream process or
      submitted by the investigator.
    </div>
    <br />
    <br />
    <md-table md-card class="criteria-table">
      <md-table-row>
        <md-table-head>Platform</md-table-head>
        <md-table-head>Sample Type</md-table-head>
        <md-table-head>Mass/Molarity to Pass</md-table-head>
        <md-table-head>Mass/Molarity to Try</md-table-head>
        <md-table-head>Requirements to Pass</md-table-head>
        <md-table-head>Requirements to Try</md-table-head>
        <md-table-head>Volume Requirements</md-table-head>
      </md-table-row>
      <md-table-row>
        <md-table-cell>10X Genomics</md-table-cell>
        <md-table-cell>cDNA</md-table-cell>
        <md-table-cell class="pass">25ng</md-table-cell>
        <md-table-cell class="try">1ng</md-table-cell>
        <md-table-cell colspan="2">No quality requirements</md-table-cell>
        <md-table-cell>N/A</md-table-cell>
      </md-table-row>
      <!-- <md-table-row>
        <md-table-cell>Libraries for Targeted Capture</md-table-cell>
        <md-table-cell>IGO or DMP libraries</md-table-cell>
        <md-table-cell class="pass"></md-table-cell>
        <md-table-cell class="try"></md-table-cell>
        <md-table-cell class="pass"></md-table-cell>
        <md-table-cell class="try"></md-table-cell>
        <md-table-cell></md-table-cell>
      </md-table-row>
      <md-table-row>
        <md-table-cell>Libraries for WES Capture</md-table-cell>
        <md-table-cell>IGO or DMP libraries</md-table-cell>
        <md-table-cell class="pass"></md-table-cell>
        <md-table-cell class="try"></md-table-cell>
        <md-table-cell class="pass"></md-table-cell>
        <md-table-cell class="try"></md-table-cell>
        <md-table-cell></md-table-cell>
      </md-table-row> -->
      <md-table-row>
        <md-table-cell rowspan="2">Libraries for Sequencing</md-table-cell>
        <md-table-cell>Individual Libraries</md-table-cell>
        <md-table-cell rowspan="2" class="pass">1.5nM</md-table-cell>
        <md-table-cell rowspan="2" class="try">1nM</md-table-cell>
        <md-table-cell rowspan="2" class="pass">150 &lt; bp &lt; 1000bp</md-table-cell>
        <md-table-cell rowspan="2" class="try">bp &lt; 150</md-table-cell>
        <md-table-cell>&GreaterEqual;20&#181;L</md-table-cell>
      </md-table-row>
      <md-table-row>
        <md-table-cell>Pooled Libraries</md-table-cell>
        <md-table-cell>&GreaterEqual;20&#181;L</md-table-cell>
      </md-table-row>
      <md-table-row>
        <md-table-cell>PDX/xenograft-derived samples</md-table-cell>
        <md-table-cell></md-table-cell>
        <md-table-cell class="pass">20ng</md-table-cell>
        <md-table-cell class="try">9ng</md-table-cell>
        <md-table-cell class="pass">60% human</md-table-cell>
        <md-table-cell class="try">50% human</md-table-cell>
        <md-table-cell>&leq;9&#181;L</md-table-cell>
      </md-table-row>
    </md-table>
  </div>
</template>

<script>
export default { name: 'OtherCriteria' };
</script>

<style></style>
