export const news = [
  {
    id: 1,
    name: "New pricing for block sequencing",
    body:
      "For investigators who make their own sequencing libraries to submit to IGO, we now have easy-to-understand block pricing for our most commonly-requested read lengths and throughputs. We accept both individual user libraries and pre-pooled libraries to occupy a full flow cell or lane. Custom read lengths and coverages outside the block pricing will still be accepted; contact us for more information.",
    date: "2020 - 10 - 26",
  },
  {
    id: 2,
    name: "End of era in IGO + new website features",
    body:
      "After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!",
    date: "2020-10-8",
  },
  {
    id: 3,
    name: "End of era in IGO + new website features",
    body:
      "After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!",
    date: "2020-10-8",
  },
  {
    id: 4,
    name: "End of era in IGO + new website features",
    body:
      "After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!",
    date: "2020-10-8",
  },
];

export const teams = [
  {
    id: 0,
    name: "Leadership",
    description: "leaders in igo",
    members: [
      { name: "Agnes Viale", role: "Director", photoName: "Viale_Agnes" },
      { name: "Neeman Mohibullah", role: "Associate Director", photoName: "Mohibullah_Neeman" },
      { name: "Kety Huberman", role: "Operations Manager", photoName: "Huberman_Kety" },
    ],
  },
  {
    id: 1,
    name: "Lab Support",
    description: "supports lab",
    members: [
      { name: "Alan Li", role: "Automation Engineer", photoName: "Li_Alan" },
      { name: "Cassidy Cobbs", role: "Scientific Liaison", photoName: "Cobbs_Cassidy" },
      { name: "Magali Cavatore", role: "Lab Manager", photoName: "Cavatore_Magali" },
      // { name: "Mary Betancor", role: "Assistant", photoName: "Betancor_Mary" },
    ],
  },
  {
    id: 2,
    name: "Sample & Project Management",
    description: "manages projects",
    members: [
      { name: "Marisa Dunigan", role: "Group Leader", photoName: "Dunigan_Marisa" },
      { name: "Meghanne Lomibao", role: "Project Coordinator", photoName: "Lomibao_Meghanne" },
      { name: "Michael Pantano", role: "Senior Project Assistant", photoName: "Pantano_Michael" },
      { name: "Zoe Steinsnyder", role: "Senior Project Assistant", photoName: "Steinsnyder_Zoe" },
    ],
  },
  {
    id: 3,
    name: "Extraction",
    description:
      "As the name implies, we are an eclectic, multidisciplinary team responsible for a diverse number of platforms. EXPAND stands for: Extraction, 10X Genomics, pathology, Archer DX, Nanostring, and digital droplet PCR, but also literally refers to our interest in integrating new platforms and advancing research technology to remain at the cutting edge for our users. \n EXPAND team extracts DNA and RNA from a variety of sample types, following validated manual and automated protocols. We work closely with our investigators to provide meaningful advice on the amount of material to submit, optimal preservation methods, and storage techniques for every sample type and desired downstream application. IGO offers a vast selection of digital PCR assays; the EXPAND team performs the processing and analysis of samples with one or more of our off-the-shelf assays, or we can help you design a new, custom assay. The digital PCR, Nanostring and Archer DX platforms aim to detect rare mutations, unknown gene rearrangements or VDJ recombination, small variations in copy number and changes in gene expression. Recently we “EXPANDed” into the single cell territory, offering the 10X Genomics platforms: cell-to-cell differences, that are often missed in bulk analysis, can be revealed at the single cell resolution. We offer all the available 10X platforms (CNV, ATAC, gene expression, TCR-seq, feature barcoding and cell hashing).The EXPAND team draws upon IGO’s philosophy of constant and open communication. It is our goal to join you in detailed, scientific discussions about your projects, to meet your needs and to work together to advance science, building long-term, trusting relationships in the process.",
    members: [
      { name: "Andrea Farina", role: "Group Leader", photoName: "Farina_Andrea" },
      { name: "Aminah Lawal", role: "Research Assistant", photoName: "Lawal_Aminah" },
      { name: "Dorothy Guzowski", role: "Senior Research Assistant", photoName: "Guzowski_Dorothy" },
      { name: "Josie D'Angelo", role: "Research Technician", photoName: "Dangelo_Josie" },
      { name: "Marisa Vanness", role: "Research Technician", photoName: "Vanness_Marisa" },
      { name: "Matthew Solowsky", role: "Senior Research Technician", photoName: "Solowsky_Matthew" },
      { name: "Tony Deblasio", role: "Senior Research Assistant", photoName: "Deblasio_Tony" },
    ],
  },
  {
    id: 4,
    name: "Library Preparation",
    description: "prepares libraries",
    members: [
      { name: "Ruchi Patel", role: "Group Leader", photoName: "Patel_Ruchi" },
      { name: "Alber Michaeel", role: "Automation Engineer", photoName: "Michaeel_Alber" },
      { name: "Elevit Perez", role: "Research Technician", photoName: "Perez_Elevit" },
      { name: "Jane Chan", role: "Research Assistant", photoName: "Chan_Jane" },
      { name: "Katherine Allard", role: "Research Assistant", photoName: "Allard_Katherine" },
      { name: "Satish Ramakrishnan", role: "Research Assistant", photoName: "Ramakrishnan_Satish" },
      { name: "Satoko Murakami", role: "Research Assistant", photoName: "Murakami_Satoko" },
    ],
  },
  {
    id: 5,
    name: "Sequencing",
    description: "sequences libraries",
    members: [
      { name: "Liping Sun", role: "Group Leader", photoName: "Sun_Liping" },
      { name: "Cuijie Lu", role: "Research Assistant", photoName: "Lu_Cuijie" },
      { name: "Jim Chen", role: "Senior Research Technician", photoName: "Chen_Jim" },
      { name: "Keumsil Hwang", role: "Senior Research Assistant", photoName: "Hwang_Keumsil" },
      { name: "Robert Hong", role: "Senior Research Technician", photoName: "Hong_Robert" },
    ],
  },
  {
    id: 6,
    name: "Data",
    description: "programming support",
    members: [
      { name: "David Mcmanamon", role: "Group Leader", photoName: "Mcmanamon_David" },
      { name: "Lisa Wagner", role: "BioInf. Software Engineer", photoName: "Wagner_Lisa" },
      { name: "Ajay Sharma", role: "BioInf. Software Engineer", photoName: "Sharma_Ajay" },
      { name: "Anna Patruno", role: "Application Analyst", photoName: "Patruno_Anna" },
      { name: "Darrell Nabors", role: "BioInf. Software Engineer", photoName: "Nabors_Darrell" },
      { name: "David Streid", role: "BioInf. Software Engineer", photoName: "Streid_David" },
    ],
  },
  {
    id: 7,
    name: "Research & Development",
    description: "researches new applications",
    members: [
      { name: "Neeman Mohibullah", role: "Group Leader", photoName: "Mohibullah_Neeman" },
      { name: "Juan Li", role: "Manager", photoName: "Li_Juan" },
      { name: "Justin Clarke", role: "Research Technician", photoName: "Clarke_Justin" },
      { name: "Taylor Allen", role: "Research Technician", photoName: "Allen_Taylor" },
    ],
  },
];

export const bulkServices = [
  {
    id: 0,
    name: "Whole Exome Sequencing",
    description: "A capture-based assay to assess the entire exome.",
    startingMaterial: "DNA or DMP Library",
    libraryChemistry: "KAPA Hyper",
    captureChemistry: "xGen v1.0 from IDT (human) SureSelectXT from Agilent (mouse)",
    sequencingReadLength: "PE100",
    sequencingCoverage: "Varies (see below)",
    deliverable: "FASTQ; analysis options available from CMO or BIC",
    tableHeaders: ["sampleCoverage", "sampleCost"],
    table: [
      { sampleCoverage: 30, sampleCost: 458 },
      { sampleCoverage: 70, sampleCost: 580 },
      { sampleCoverage: 100, sampleCost: 668 },
      { sampleCoverage: 150, sampleCost: 808 },
      { sampleCoverage: 200, sampleCost: 966 },
      { sampleCoverage: 250, sampleCost: 1106 },
    ],
  },
  {
    id: 1,
    name: "Targeted Sequencing",
    description: "Capture-based assays to assess specific genes within the exome.",
    startingMaterial: "DNA or DMP Library",
    libraryChemistry: "KAPA Hyper",
    captureChemistry: "Custom probes from IDT",
    sequencingReadLength: "PE100",
    sequencingCoverage: "500X T/250X N (IMPACT/HemePACT); 1000X (ACCESS)",
    deliverable: "cBioPortal instance",
    tableHeaders: ["panel", "sampleType", "sampleCost"],
    table: [
      { panel: "IMPACT", sampleType: "Tumor", sampleCost: 500 },
      { panel: "IMPACT", sampleType: "Normal", sampleCost: 250 },
      { panel: "Mouse IMPACT", sampleType: "", sampleCost: 419 },
      { panel: "HemePACT", sampleType: "Tumor", sampleCost: 573 },
      { panel: "HemePACT", sampleType: "Normal", sampleCost: 350 },
      { panel: "ACCESS", sampleType: "Tumor", sampleCost: 600 },
      { panel: "ACCESS", sampleType: "Normal", sampleCost: 300 },
    ],
  },
  {
    id: 2,
    name: "Transcriptome Sequencing",
    description: "Techniques to enrich RNA and assess expressed transcripts",
    startingMaterial: "RNA or cells (SMARTer only)",
    libraryChemistry: "TruSeq stranded mRNA (polyA), TruSeq stranded total (Ribodepletion), SMART-Seq v4 + KAPA Hyper (SMARTer)",
    sequencingReadLength: "PE50 or PE100",
    sequencingCoverage: "20-100M",
    deliverable: "FASTQ; analysis options from BIC",
    tableHeaders: ["libraryType", "readNumber", "sampleCostPe50", "sampleCostPe100"],
    table: [
      { libraryType: "PolyA", readNumber: "20-30", sampleCostPe50: 388, sampleCostPe100: 425 },
      { libraryType: "PolyA", readNumber: "30-40", sampleCostPe50: 450, sampleCostPe100: 497 },
      { libraryType: "PolyA", readNumber: "40-50", sampleCostPe50: 524, sampleCostPe100: 581 },
      { libraryType: "PolyA", readNumber: "50-60", sampleCostPe50: 563, sampleCostPe100: 637 },
      { libraryType: "PolyA", readNumber: "60-80", sampleCostPe50: 648, sampleCostPe100: 746 },
      { libraryType: "PolyA", readNumber: "80-100", sampleCostPe50: 777, sampleCostPe100: 895 },
      { libraryType: "RiboDepletion", readNumber: "20-30", sampleCostPe50: 440, sampleCostPe100: 477 },
      { libraryType: "RiboDepletion", readNumber: "30-40", sampleCostPe50: 511, sampleCostPe100: 558 },
      { libraryType: "RiboDepletion", readNumber: "40-50", sampleCostPe50: 568, sampleCostPe100: 625 },
      { libraryType: "RiboDepletion", readNumber: "50-60", sampleCostPe50: 624, sampleCostPe100: 698 },
      { libraryType: "RiboDepletion", readNumber: "60-80", sampleCostPe50: 709, sampleCostPe100: 807 },
      { libraryType: "RiboDepletion", readNumber: "80-100", sampleCostPe50: 839, sampleCostPe100: 956 },
      { libraryType: "SMARTer", readNumber: "20-30", sampleCostPe50: 478, sampleCostPe100: 515 },
      { libraryType: "SMARTer", readNumber: "30-40", sampleCostPe50: 540, sampleCostPe100: 587 },
      { libraryType: "SMARTer", readNumber: "40-50", sampleCostPe50: 614, sampleCostPe100: 671 },
      { libraryType: "SMARTer", readNumber: "50-60", sampleCostPe50: 653, sampleCostPe100: 727 },
      { libraryType: "SMARTer", readNumber: "60-80", sampleCostPe50: 738, sampleCostPe100: 836 },
      { libraryType: "SMARTer", readNumber: "80-100", sampleCostPe50: 867, sampleCostPe100: 985 },
    ],
  },
  {
    id: 3,
    name: "Whole Genome Sequencing",
    description: "Assess the entire genome using PCR-free methods or minimal PCR cycles.",
    startingMaterial: "DNA",
    libraryChemistry: "KAPA Hyper",
    sequencingReadLength: "PE150",
    sequencingCoverage: "Varies; see below",
    deliverable: "FASTQ",
    tableHeaders: ["sampleCoverage", "sampleCostFrozen", "sampleCostFfpe"],
    table: [
      { sampleCoverage: 30, sampleCostFrozen: 1067, sampleCostFfpe: 1263 },
      { sampleCoverage: 40, sampleCostFrozen: 1324, sampleCostFfpe: 1655 },
      { sampleCoverage: 50, sampleCostFrozen: 1557, sampleCostFfpe: 2046 },
      { sampleCoverage: 60, sampleCostFrozen: 1769, sampleCostFfpe: 2437 },
      { sampleCoverage: 80, sampleCostFrozen: 2229, sampleCostFfpe: 3219 },
      { sampleCoverage: 100, sampleCostFrozen: 3017, sampleCostFfpe: 4002 },
      { sampleCoverage: 150, sampleCostFrozen: 4009, sampleCostFfpe: 5957 },
    ],
  },
  {
    id: 4,
    name: "Epigenome Sequencing",
    description: "Various methods to assess the epigenetic structure of the genome",
    startingMaterial: "Cells (ATAC), Transposed DNA (ChIP), DNA – samples in multiples of 4 (EPIC)",
    libraryChemistry: "Nextera XT (ATAC), KAPA HTP (ChIP), TruSeq Methyl Capture (EPIC)",
    sequencingReadLength: "PE50 (ATAC & ChIP), PE100 (EPIC)",
    sequencingCoverage: "40-50M (ATAC), 30-40M (ChIP), 40M (EPIC)",
    deliverable: "FASTQ",
    tableHeaders: ["platform", "sampleCost"],
    table: [
      { platform: "ATAC-Seq", sampleCost: 589 },
      { platform: "ChIP-Seq", sampleCost: 351 },
      { platform: "EPIC Methyl Capture-Seq", sampleCost: 657 },
    ],
  },
  {
    id: 5,
    name: "Other Services",
    description: "Please email us if your sequencing needs do not fit in one of these categories.",
    tableHeaders: ["platform", "sequencingDetails", "deliverable", "cost"],
    table: [
      { platform: "Shallow WGS", sequencingDetails: "PE100, 10M reads", deliverable: "FASTQ + CNV analysis", cost: "$182" },
      { platform: "Amplicon Sequencing", sequencingDetails: "Varies", deliverable: "FASTQ", cost: "please inquire" },
      {
        platform: "CRISPR Cut Site Sequencing",
        sequencingDetails: "75K reads",
        deliverable: "FASTQ + CRISPRESSO analysis",
        cost: "$70",
      },
      { platform: "Library Sequencing", sequencingDetails: "varies", deliverable: "FASTQ", cost: "please inquire" },
      {
        platform: "Archer FusionPlex",
        sequencingDetails: "Solid Tumor Panel",
        deliverable: "Archer portal access",
        cost: "$820 + sequencing",
      },
      {
        platform: "Archer FusionPlex",
        sequencingDetails: "Heme Panel",
        deliverable: "Archer portal access",
        cost: "$610 + sequencing",
      },
    ],
  },
];

export const singleServices = [
  {
    id: 0,
    name: "10x Genomics Single Cell",
    description:
      "Single-cell platforms to interrogate gene expression, immune repertoire, epigenetic factors, copy number, and/or protein expression.",
    startingMaterial: "Single cell or nuclei suspension",
    libraryChemistry: "Chromium Single Cell",
    sequencingReadLength: "PE28/91 (3’GEX), PE26/91 (5’GEX), PE150 (V(D)J), PE50 (ATAC), PE100 or PE150 (CNV)",
    sequencingCoverage: "20K reads/cell (GEX), 5K reads/cell (V(D)J & cell hashing), 25K reads/cell (ATAC), 750K reads/cell (CNV)",
    deliverable: "FASTQ, CellRanger output",
    tableHeaders: ["xGenomicsPlatform", "sampleCostLibrary", "sampleCostSequencing"],
    table: [
      { xGenomicsPlatform: "5′ OR 3′ Gene Expression", sampleCostLibrary: 2068, sampleCostSequencing: "$0.07-$0.13" },
      { xGenomicsPlatform: "5′ Gene Expression + V(D)J Enrichment", sampleCostLibrary: 2279, sampleCostSequencing: "$0.12-$0.20" },
      { xGenomicsPlatform: "Feature Barcoding/Cell Hash Add-on", sampleCostLibrary: 116, sampleCostSequencing: "$0.05-$0.07" },
      { xGenomicsPlatform: "Copy Number Variation", sampleCostLibrary: 2191, sampleCostSequencing: "$3" },
      { xGenomicsPlatform: "ATAC-Seq", sampleCostLibrary: 2075, sampleCostSequencing: "$0.06-$0.17" },
    ],
  },
  {
    id: 1,
    name: "10x Genomics Visium",
    description: "Transcriptome sequencing of 1-10 cells along with spatial information.",
    startingMaterial: "Fresh tissue",
    libraryChemistry: "Visium Spatial Gene Expression",
    sequencingReadLength: "PE28/90",
    sequencingCoverage: "50K reads/1-10 cells",
    deliverable: "FASTQ, SpaceRanger output",
    tissueOptimizationCost: "$1,345 (once/tissue)",
    libraryCost: "$4,785/slide",
    sequencingCost: "$5,232 x %Area of squares covered",
  },
  {
    id: 2,
    name: "Mission Bio Tapestri",
    description: "A targeted single-cell platform to detect SNVs and CNVs in off-the-shelf or custom panels.",
    startingMaterial: "Single cell or nuclei suspension",
    sequencingReadLength: "PE150",
    sequencingCoverage: "Panel dependent",
    deliverable: "FASTQ + Tapestri Platform output",
    cost: "$2,800/sample",
  },
  {
    id: 3,
    name: "PlateSeq",
    description:
      "A single- or low-cell Smart-seq 2 method to accommodate projects without enough cells for 10X Genomics, or users interested in capturing the entire body of the gene.",
    startingMaterial: "Sorted cells",
    libraryChemistry: "SMART-Seq + Nextera XT",
    sequencingReadLength: "PE50",
    sequencingCoverage: "5M reads/cell",
    deliverable: "FASTQ",
    libraryCost: "$1,680/plate",
    sequencingCost: "$17.50/cell",
  },
];

export const otherServices = [
  {
    id: 0,
    name: "Digital PCR",
    description:
      "PCR-based services for mutation detection, fusion detection, viral detection, or CNV. Hundreds of assays have been validated commercially or in house, but if your gene of interest is not on the list, IGO offers design & optimization services.",
    startingMaterial: "DNA, RNA, Library",
    deliverable: "Report",
    tableHeaders: ["service", "cost"],
    table: [
      { service: "New Assay Design & Optimization", cost: 400 },
      { service: "New Assay Order (CNV)", cost: 200 },
      { service: "New Assay Order (mutation)", cost: 375 },
      { service: "Digital PCR (per reaction)", cost: 9.5 },
    ],
  },
  {
    id: 1,
    name: "Cell Line Authentication",
    description: "STR-based analysis to verify the identity of cell lines grown in vitro.",
    startingMaterial: "DNA",
    kitChemistry: "AmpFLSTR Identifiler (human), Custom (mouse; pending)",
    deliverable: "Genotype + Database matching report",
    tableHeaders: ["species", "cost"],
    table: [
      { species: "Human", cost: 36 },
      { species: "Mouse", cost: 44 },
    ],
  },
  {
    id: 2,
    name: "Tissue and Bulk Extraction",
    description: "Manual and automated methods for purifying RNA, DNA, or both from a variety of starting materials and sample types.",
    startingMaterial: "See below. Other? Contact us.",
    deliverable: "Nucleic acid + QC report",
    tableHeaders: ["startingMaterial", "extractionOutput", "sampleCost"],
    table: [
      { startingMaterial: "Fresh frozen, OCT, or viably frozen tissue/cells", extractionOutput: "DNA", sampleCost: 25 },
      { startingMaterial: "Blood", extractionOutput: "DNA", sampleCost: 30 },
      { startingMaterial: "FFPE tissue", extractionOutput: "DNA", sampleCost: 35 },
      { startingMaterial: "Fingernails", extractionOutput: "DNA", sampleCost: 40 },
      { startingMaterial: "Frozen tissue/cells", extractionOutput: "RNA", sampleCost: 33 },
      { startingMaterial: "Frozen tissue/cells + COVID19 testing", extractionOutput: "RNA", sampleCost: 93 },
      { startingMaterial: "FFPE tissue", extractionOutput: "RNA", sampleCost: 39 },
      { startingMaterial: "All materials", extractionOutput: "DNA + RNA (simultaneous extraction)", sampleCost: 55 },
    ],
  },
  {
    id: 3,
    name: "User Library Sequencing",
    description: "Illumina sequencing of user-prepared libraries.",
    startingMaterial: "DNA libraries",
    sequencingReadLength: "Varies (see below); contact us for additional options",
    sequencingCoverage: "Varies (see below); contact us for additional options",
    deliverable: "FASTQ",
    tableHeaders: ["totalReads", "pe50", "pe100", "pe150", "special28"],
    table: [
      { totalReads: "120M", pe50: 1092, pe100: 1746, pe150: 1746, special28: 1092 },
      { totalReads: "350M", pe50: 1414, pe100: 2035, pe150: 2820, special28: 2035 },
      { totalReads: "350M Rush", pe50: 3287, pe100: 4623, pe150: 5467, special28: 4623 },
      { totalReads: "1800M", pe50: 4881, pe100: 6613, pe150: 7727, special28: 6613 },
    ],
  },
  {
    id: 4,
    name: "General Services",
    description: "Other services offered by IGO.",
    tableHeaders: ["serviceType", "serviceSubType", "price"],
    table: [
      { serviceType: "QC Service", serviceSubType: "BioAnalyzer or TapeStation QC", price: "$11/sample" },
      { serviceType: "QC Service", serviceSubType: "Qubit/Quant-it", price: "$7/sample" },
      { serviceType: "QC Service", serviceSubType: "%Human for PDX", price: "$19/sample" },
      { serviceType: "Pathology Service", serviceSubType: "Sectioning (curls)", price: "$15/block" },
      { serviceType: "Pathology Service", serviceSubType: "Sectioning (slides)", price: "$3.50/sample" },
      { serviceType: "Pathology Service", serviceSubType: "H&E Staining", price: "$7/sample" },
      { serviceType: "Pathology Service", serviceSubType: "Slide scraping", price: "$10/sample" },
      { serviceType: "Pathology Service", serviceSubType: "Macrodissection", price: "$3/slide" },
    ],
  },
];

export const archerFusionGenes = [
  ["ACVR2A", "AKT1", "ALK", "AR", "ARAF"],
  ["ARHGAP26", "BCOR", "BCORL1", "BRAF", "BRD4"],
  ["CAMTA1", "CCNB3", "CIC", "CSF1", "DNAJB1"],
  ["EGFR", "EPC1", "ERBB2", "ERBB3", "ERBB4"],
  ["ERG", "ESR1", "ETV1", "ETV4", "ETV5"],
  ["ETV6", "EWSR1", "FGF1", "FGFR1", "FGFR2"],
  ["FGFR3", "FGFR4", "FGR", "FLT1", "FLT3"],
  ["FOS", "FOSB", "FOXO1", "FOXR2", "FUS"],
  ["NCOA1", "NCOA2", "NCOA3", "NFATC2", "NFE2L2"],
  ["NOTCH1", "NOTCH2", "NR4A3", "NRG1", "NTRK1"],
  ["NTRK2", "NTRK3", "NUTM1", "NUTM2A", "NUTM2B"],
  ["PAX3", "PAX5", "PAX7", "PDGFB", "PDGFD"],
  ["PDGFRA", "PDGFRB", "PGR", "PHF1", "PIK3CA"],
  ["PLAG1", "PPARG", "PRB3", "PRKACA", "PRKACB"],
  ["PRKCA", "PRKCB", "PRKD1", "PRKD2", "PRKD3"],
  ["PTCH1", "PTPN1", "RAD51B", "RAF1", "RELA"],
  ["RET", "RLF", "ROS1", "RSPO2", "RSPO3"],
  ["SRF", "SS18", "SS18L1", "STAT6", "TAF15"],
  ["TCF12", "TERT", "TFE3", "TFEB", "TFG"],
  ["THADA", "TMPRSS2", "USP6", "VGLL2", "VGLL3"],
  ["WWTR1", "YAP1", "YWHAE"],
];
