export const news = [
  {
    id: 1,
    name: "New pricing for block sequencing",
    body:
      "For investigators who make their own sequencing libraries to submit to IGO, we now have easy-to-understand block pricing for our most commonly-requested read lengths and throughputs. We accept both individual user libraries and pre-pooled libraries to occupy a full flow cell or lane. Custom read lengths and coverages outside the block pricing will still be accepted; contact us for more information.",
    date: "2020 - 10 - 26",
  },
  {
    id: 2,
    name: "End of era in IGO + new website features",
    body:
      "After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!",
    date: "2020-10-8",
  },
  {
    id: 3,
    name: "End of era in IGO + new website features",
    body:
      "After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!",
    date: "2020-10-8",
  },
  {
    id: 4,
    name: "End of era in IGO + new website features",
    body:
      "After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!",
    date: "2020-10-8",
  },
];

export const teams = [
  {
    id: 0,
    name: "Leadership",
    description: "leaders in igo",
    members: [
      { name: "Agnes Viale", role: "Director", photoName: "Viale_Agnes" },
      { name: "Neeman Mohibullah", role: "Associate Director", photoName: "Mohibullah_Neeman" },
      { name: "Kety Huberman", role: "Operations Manager", photoName: "Huberman_Kety" },
    ],
  },
  {
    id: 1,
    name: "Lab Support",
    description: "supports lab",
    members: [
      { name: "Alan Li", role: "Automation Engineer", photoName: "Li_Alan" },
      { name: "Cassidy Cobbs", role: "Scientific Liaison", photoName: "Cobbs_Cassidy" },
      { name: "Magali Cavatore", role: "Lab Manager", photoName: "Cavatore_Magali" },
      // { name: "Mary Betancor", role: "Assistant", photoName: "Betancor_Mary" },
    ],
  },
  {
    id: 2,
    name: "Sample & Project Management",
    description: "manages projects",
    members: [
      { name: "Marisa Dunigan", role: "Group Leader", photoName: "Dunigan_Marisa" },
      { name: "Meghanne Lomibao", role: "Project Coordinator", photoName: "Lomibao_Meghanne" },
      { name: "Michael Pantano", role: "Senior Project Assistant", photoName: "Pantano_Michael" },
      { name: "Zoe Steinsnyder", role: "Senior Project Assistant", photoName: "Steinsnyder_Zoe" },
    ],
  },
  {
    id: 3,
    name: "EXPAND",
    description:
      "As the name implies, we are an eclectic, multidisciplinary team responsible for a diverse number of platforms. EXPAND stands for: Extraction, 10X Genomics, pathology, Archer DX, Nanostring, and digital droplet PCR, but also literally refers to our interest in integrating new platforms and advancing research technology to remain at the cutting edge for our users. \n EXPAND team extracts DNA and RNA from a variety of sample types, following validated manual and automated protocols. We work closely with our investigators to provide meaningful advice on the amount of material to submit, optimal preservation methods, and storage techniques for every sample type and desired downstream application. IGO offers a vast selection of digital PCR assays; the EXPAND team performs the processing and analysis of samples with one or more of our off-the-shelf assays, or we can help you design a new, custom assay. The digital PCR, Nanostring and Archer DX platforms aim to detect rare mutations, unknown gene rearrangements or VDJ recombination, small variations in copy number and changes in gene expression. Recently we “EXPANDed” into the single cell territory, offering the 10X Genomics platforms: cell-to-cell differences, that are often missed in bulk analysis, can be revealed at the single cell resolution. We offer all the available 10X platforms (CNV, ATAC, gene expression, TCR-seq, feature barcoding and cell hashing).The EXPAND team draws upon IGO’s philosophy of constant and open communication. It is our goal to join you in detailed, scientific discussions about your projects, to meet your needs and to work together to advance science, building long-term, trusting relationships in the process.",
    members: [
      { name: "Andrea Farina", role: "Group Leader", photoName: "Farina_Andrea" },
      { name: "Aminah Lawal", role: "Research Assistant", photoName: "Lawal_Aminah" },
      { name: "Dorothy Guzowski", role: "Senior Research Assistant", photoName: "Guzowski_Dorothy" },
      { name: "Josie D'Angelo", role: "Research Technician", photoName: "Dangelo_Josie" },
      { name: "Marisa Vanness", role: "Research Technician", photoName: "Vanness_Marisa" },
      { name: "Matthew Solowsky", role: "Senior Research Technician", photoName: "Solowsky_Matthew" },
      { name: "Tony Deblasio", role: "Senior Research Assistant", photoName: "Deblasio_Tony" },
    ],
  },
  {
    id: 4,
    name: "Library Preparation",
    description: "prepares libraries",
    members: [
      { name: "Ruchi Patel", role: "Group Leader", photoName: "Patel_Ruchi" },
      { name: "Alber Michaeel", role: "Automation Engineer", photoName: "Michaeel_Alber" },
      { name: "Elevit Perez", role: "Research Technician", photoName: "Perez_Elevit" },
      { name: "Jane Chan", role: "Research Assistant", photoName: "Chan_Jane" },
      { name: "Katherine Allard", role: "Research Assistant", photoName: "Allard_Katherine" },
      { name: "Satish Ramakrishnan", role: "Research Assistant", photoName: "Ramakrishnan_Satish" },
      { name: "Satoko Murakami", role: "Research Assistant", photoName: "Murakami_Satoko" },
    ],
  },
  {
    id: 5,
    name: "Sequencing Team",
    description: "sequences libraries",
    members: [
      { name: "Liping Sun", role: "Group Leader", photoName: "Sun_Liping" },
      { name: "Cuijie Lu", role: "Research Assistant", photoName: "Lu_Cuijie" },
      { name: "Jim Chen", role: "Senior Research Technician", photoName: "Chen_Jim" },
      { name: "Keumsil Hwang", role: "Senior Research Assistant", photoName: "Hwang_Keumsil" },
      { name: "Robert Hong", role: "Senior Research Technician", photoName: "Hong_Robert" },
    ],
  },
  {
    id: 6,
    name: "Data Team",
    description: "programming support",
    members: [
      { name: "David Mcmanamon", role: "Group Leader", photoName: "Mcmanamon_David" },
      { name: "Lisa Wagner", role: "BioInf. Software Engineer", photoName: "Wagner_Lisa" },
      { name: "Ajay Sharma", role: "BioInf. Software Engineer", photoName: "Sharma_Ajay" },
      { name: "Anna Patruno", role: "Application Analyst", photoName: "Patruno_Anna" },
      { name: "Darrell Nabors", role: "BioInf. Software Engineer", photoName: "Nabors_Darrell" },
      { name: "David Streid", role: "BioInf. Software Engineer", photoName: "Streid_David" },
    ],
  },
  {
    id: 7,
    name: "Research & Development",
    description: "researches new applications",
    members: [
      { name: "Neeman Mohibullah", role: "Group Leader", photoName: "Mohibullah_Neeman" },
      { name: "Juan Li", role: "Manager", photoName: "Li_Juan" },
      { name: "Justin Clarke", role: "Research Technician", photoName: "Clarke_Justin" },
      { name: "Taylor Allen", role: "Research Technician", photoName: "Allen_Taylor" },
    ],
  },
];

export const services = [
  {
    id: 0,
    name: "Whole Exome Sequencing",
    description: "A capture-based assay to assess the entire exome.",
    startingMaterial: "DNA or DMP Library",
    libraryChemistry: "KAPA Hyper",
    captureChemistry: "xGen v1.0 from IDT (human) SureSelectXT from Agilent (mouse)",
    sequencingReadLength: "PE100",
    sequencingCoverage: "Varies (see below)",
    deliverable: "FASTQ; analysis options available from CMO or BIC",
    table: [
      { coverage: 30, cost: 458 },
      { coverage: 70, cost: 580 },
      { coverage: 100, cost: 668 },
      { coverage: 150, cost: 808 },
      { coverage: 200, cost: 966 },
      { coverage: 250, cost: 1106 },
    ],
  },
  {
    id: 1,
    name: "Targeted Sequencing",
    description: "Capture-based assays to assess specific genes within the exome.",
    startingMaterial: "DNA or DMP Library",
    libraryChemistry: "KAPA Hyper",
    captureChemistry: "Custom probes from IDT",
    sequencingReadLength: "PE100",
    sequencingCoverage: "500X T/250X N (IMPACT/HemePACT); 1000X (ACCESS)",
    deliverable: "cBioPortal instance",
    tableHeaders: ["coverage", "cost"],
    table: [
      { coverage: 30, cost: 458 },
      { coverage: 70, cost: 580 },
      { coverage: 100, cost: 668 },
      { coverage: 150, cost: 808 },
      { coverage: 200, cost: 966 },
      { coverage: 250, cost: 1106 },
    ],
  },
  {
    id: 2,
    name: "Transcriptome Sequencing",
    description: "Techniques to enrich RNA and assess expressed transcripts",
    startingMaterial: "RNA or cells (SMARTer only)",
    libraryChemistry: "TruSeq stranded mRNA (polyA), TruSeq stranded total (Ribodepletion), SMART-Seq v4 + KAPA Hyper (SMARTer)",
    sequencingReadLength: "PE50 or PE100",
    sequencingCoverage: "20-100M",
    deliverable: "FASTQ; analysis options from BIC",
    table: [
      { coverage: 30, cost: 458 },
      { coverage: 70, cost: 580 },
      { coverage: 100, cost: 668 },
      { coverage: 150, cost: 808 },
      { coverage: 200, cost: 966 },
      { coverage: 250, cost: 1106 },
    ],
  },
  {
    id: 3,
    name: "Whole Genome Sequencing",
    description: "Assess the entire genome using PCR-free methods or minimal PCR cycles.",
    startingMaterial: "DNA",
    libraryChemistry: "KAPA Hyper",
    sequencingReadLength: "PE150",
    sequencingCoverage: "Varies; see below",
    deliverable: "FASTQ",
    table: [
      { coverage: 30, cost: 458 },
      { coverage: 70, cost: 580 },
      { coverage: 100, cost: 668 },
      { coverage: 150, cost: 808 },
      { coverage: 200, cost: 966 },
      { coverage: 250, cost: 1106 },
    ],
  },
  {
    id: 3,
    name: "Whole Genome Sequencing",
    description: "Assess the entire genome using PCR-free methods or minimal PCR cycles.",
    startingMaterial: "DNA",
    libraryChemistry: "KAPA Hyper",
    sequencingReadLength: "PE150",
    sequencingCoverage: "Varies; see below",
    deliverable: "FASTQ",
    table: [
      { coverage: 30, cost: 458 },
      { coverage: 70, cost: 580 },
      { coverage: 100, cost: 668 },
      { coverage: 150, cost: 808 },
      { coverage: 200, cost: 966 },
      { coverage: 250, cost: 1106 },
    ],
  },
  {
    id: 4,
    name: "Epigenome Sequencing",
    description: "Various methods to assess the epigenetic structure of the genome",
    startingMaterial: "Cells (ATAC), Transposed DNA (ChIP), DNA – samples in multiples of 4 (EPIC)",
    libraryChemistry: "Nextera XT (ATAC), KAPA HTP (ChIP), TruSeq Methyl Capture (EPIC)",
    sequencingReadLength: "PE50 (ATAC & ChIP), PE100 (EPIC)",
    sequencingCoverage: "40-50M (ATAC), 30-40M (ChIP), 40M (EPIC)",
    deliverable: "FASTQ",
    table: [
      { coverage: 30, cost: 458 },
      { coverage: 70, cost: 580 },
      { coverage: 100, cost: 668 },
      { coverage: 150, cost: 808 },
      { coverage: 200, cost: 966 },
      { coverage: 250, cost: 1106 },
    ],
  },
];
