export const news = [
  {
    id: 1,
    name: 'New pricing for block sequencing',
    body:
      'For investigators who make their own sequencing libraries to submit to IGO, we now have easy-to-understand block pricing for our most commonly-requested read lengths and throughputs. We accept both individual user libraries and pre-pooled libraries to occupy a full flow cell or lane. Custom read lengths and coverages outside the block pricing will still be accepted; contact us for more information.',
    date: '2020 - 10 - 26',
  },
  {
    id: 2,
    name: 'End of era in IGO + new website features',
    body:
      'After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!',
    date: '2020-10-8',
  },
  {
    id: 3,
    name: 'End of era in IGO + new website features',
    body:
      'After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!',
    date: '2020-10-8',
  },
  {
    id: 4,
    name: 'End of era in IGO + new website features',
    body:
      'After more than 6 months and over 46,000 samples, Friday, October 9 will be the last day of COVID-19 testing in IGO. While the core jumped at the opportunity to support our colleagues and city through the ongoing pandemic, we also look forward to turning our full attention back to our mission of supporting and enabling a broad range of research efforts at MSK. We will continue to provide COVID-19 testing of research samples. In addition to the new 10X Genomics Visium platform, we are improving our website resources for investigators. A searchable, comprehensive list of our ddPCR assays is now available and stay tuned for a project tracker, currently in beta testing!',
    date: '2020-10-8',
  },
];

export const teams = [
  {
    id: 0,
    name: 'Leadership',
    description:
      'The leadership team oversees over 40 full-time staff from entry-level research technicians to senior experts. They not only ensure that everyone is working in concert to process thousands of projects each year, but also continue to bring on new technologies to keep IGO on the cutting edge of genome science.',
    members: [
      { name: 'Agnes Viale', role: 'Director', photoName: 'Viale_Agnes' },
      { name: 'Neeman Mohibullah', role: 'Associate Director', photoName: 'Mohibullah_Neeman' },
      { name: 'Kety Huberman', role: 'Operations Manager', photoName: 'Huberman_Kety' },
    ],
  },
  {
    id: 1,
    name: 'Lab Support',
    description:
      'As a large, high-throughput facility constantly striving for technical excellence and exemplary customer service, IGO has several employees who work between and among teams and directly with investigators.',
    members: [
      { name: 'Alan Li', role: 'Automation Engineer', photoName: 'Li_Alan' },
      { name: 'Cassidy Cobbs', role: 'Scientific Liaison', photoName: 'Cobbs_Cassidy' },
      { name: 'Magali Cavatore', role: 'Lab Manager', photoName: 'Cavatore_Magali' },
      { name: 'Mary Betancor', role: 'SKI Administrative Assistant II', photoName: 'Betancor_Mary' },
    ],
  },
  {
    id: 2,
    name: 'Sample & Project Management',
    description:
      'The SPM team works with investigators to quickly and correctly accession and QC all samples that come into IGO, including helping with navigation of iLab, easing sample webform submissions, facilitating smooth processing, and providing updates to investigators.',
    members: [
      { name: 'Marisa Dunigan', role: 'Supervisor, IGO', photoName: 'Dunigan_Marisa' },
      { name: 'Emily Brennan', role: 'Project Assistant', photoName: 'Brennan_Emily' },
      { name: 'Meghanne Lomibao', role: 'Project Coordinator', photoName: 'Lomibao_Meghanne' },
      { name: 'Tressa Octave', role: 'Senior Project Assistant', photoName: 'Octave_Tressa' },
      { name: 'Valerie Patritti', role: 'Project Manager', photoName: 'Patritti_Valerie' },
      { name: 'Position Opening Soon!', role: 'Senior Project Assistant' },
    ],
  },
  {
    id: 3,
    name: 'EXPAND',
    description:
      'EXPAND stands for: Extraction, pathology, Archer DX, and digital droplet PCR, but also literally refers to their interest in integrating new platforms and advancing research technology to remain at the cutting edge for our users. The EXPAND team draws upon IGO’s philosophy of constant and open communication and aims to join you in detailed, scientific discussions about your projects, to meet your needs and to work together to advance science, building long-term, trusting relationships in the process.',
    members: [
      { name: 'Andrea Farina', role: 'Manager, IGO', photoName: 'Farina_Andrea' },
      { name: 'Dorothy Guzowski', role: 'Senior Research Assistant', photoName: 'Guzowski_Dorothy' },
      { name: 'Jordana Barnett', role: 'Intern', photoName: 'Barnett_Jordana' },
      { name: 'Julienne Lomibao', role: 'Research Technician', photoName: 'Lomibao_Julienne' },
      { name: 'Matthew Solowsky', role: 'Senior Research Technician', photoName: 'Solowsky_Matthew' },
      { name: 'Tony Deblasio', role: 'Senior Research Assistant', photoName: 'Deblasio_Tony' },
      { name: 'Open Position!', role: 'Research Assistant' },
    ],
  },
  {
    id: 4,
    name: 'Nucleic Acids',
    description:
      "The Nucleic Acid team handles the bulk of IGO's sample processing, utilizing liquid-handling robots to automate many platforms. They also handle IGO's single cell platforms: 10X Genomics scRNASeq & Multiome, MissionBio Tapestri, PlateSeq, and DLP.",
    members: [
      { name: 'Ruchi Patel', role: 'Manager, IGO', photoName: 'Patel_Ruchi' },
      { name: 'Alber Michaeel', role: 'Automation Engineer', photoName: 'Michaeel_Alber' },
      { name: 'Elevit Perez', role: 'Senior Research Technician', photoName: 'Perez_Elevit' },
      { name: 'Justin Clarke', role: 'Research Technician', photoName: 'Clarke_Justin' },
      { name: 'Kalliopi Chatzis', role: 'Research Assistant', photoName: 'Chatzis_Kalliopi' },
      { name: 'Katherine Allard', role: 'Research Assistant', photoName: 'Allard_Katherine' },
      { name: 'Satish Ramakrishnan', role: 'Research Assistant', photoName: 'Ramakrishnan_Satish' },
      { name: 'Satoko Murakami', role: 'Research Assistant', photoName: 'Murakami_Satoko' },
      { name: 'Sophie Kleinberg', role: 'Intern', photoName: 'Kleinberg_Sophie' },
      { name: 'Yushi Wu', role: 'Research Assistant', photoName: 'Wu_Yushi' },
      { name: 'Open Position!', role: 'Research Assistant' },
      { name: 'Open Position!', role: 'Research Technician (Temporary)' },
    ],
  },
  {
    id: 5,
    name: 'Sequencing',
    description:
      "The Sequencing Team performs all activities related to Illumina sequencing, including quantity and quality assessment of libraries, pooling, and preparation for sequencing. The team is also responsible for the care & feeding of IGO's 12 sequencing instruments.",
    members: [
      { name: 'Liping Sun', role: 'Manager, IGO', photoName: 'Sun_Liping' },
      { name: 'Cuijie Lu', role: 'Research Assistant', photoName: 'Lu_Cuijie' },
      { name: 'Jim Chen', role: 'Senior Research Technician', photoName: 'Chen_Jim' },
      { name: 'Keumsil Hwang', role: 'Senior Research Assistant', photoName: 'Hwang_Keumsil' },
      { name: 'Robert Hong', role: 'Senior Research Technician', photoName: 'Hong_Robert' },
      { name: 'Open Position!', role: 'Research Assistant' },
    ],
  },
  {
    id: 6,
    name: 'Data',
    description:
      "The IGO Data Team is a group of bioinformaticians, software engineers, and computer scientists.  They work closely with IGO's investigators and wet-lab technicians to write multiple software applications from sample receiving and LIMS processing to post-sequencing stats tracking and data delivery.",
    members: [
      { name: 'David Mcmanamon', role: 'Manager, IGO', photoName: 'Mcmanamon_David' },
      { name: 'Anna Patruno', role: 'Bioinfo. Software Engineer II', photoName: 'Patruno_Anna' },
      { name: 'Darrell Nabors', role: 'Bioinformatics Engineer V', photoName: 'Nabors_Darrell' },
      { name: 'David Streid', role: 'Bioinfo. Software Engineer II', photoName: 'Streid_David' },
      { name: 'Fahimeh Mirhaj', role: 'Bioinfo. Software Engineer I', photoName: 'Mirhaj_Fahimeh' },
      // { name: 'Open Position!', role: 'Single Cell Analyst' },
    ],
  },
  {
    id: 7,
    name: 'Research & Development',
    description:
      'The R&D team develops, tests, and implements new genomics platforms for the MSKCC community. In addition to testing off-the-shelf assays, our group works with MSK investigators to bring customized platforms to IGO.',
    members: [
      { name: 'Neeman Mohibullah', role: 'Associate Director, IGO', photoName: 'Mohibullah_Neeman' },
      { name: 'Cassidy Illum', role: 'Research Technician', photoName: 'Illum_Cassidy' },
      { name: 'Elijah Castro', role: 'Research Technician', photoName: 'Castro_Elijah' },
      { name: 'Juan Li', role: 'Manager, IGO', photoName: 'Li_Juan' },
      { name: 'Open Position!', role: 'Manager' },
    ],
  },
  {
    id: 8,
    name: 'IGO Alumni',
    description:
      'IGO technicians gain valuable skills and cutting-edge knowledge while working in a fast-paced environment. Many leverage that experience into advanced degrees and training to further their careers in science and medicine.',
    members: [
      { name: 'Denise Chen', role: 'Philadelphia College of Osteopathic Medicine', photoName: 'Chen_Denise' },
      { name: 'Desmond Lambe', role: 'Rensselaer Polytechnic Institute', photoName: 'Lambe_Desmond' },
      { name: "Josie D'Angelo", role: 'UC Berkeley ', photoName: 'Dangelo_Josie' },
      { name: 'Marisa Vanness', role: 'Geisinger Commonwealth School of Medicine', photoName: 'Vanness_Marisa' },
      { name: 'Michael Pantano', role: 'BU Questrom School of Business', photoName: 'Pantano_Michael' },
      { name: 'Rosie Wenrich', role: 'Rowan University', photoName: 'Wenrich_Rosie' },
      { name: 'Taylor Allen', role: 'Georgia Tech Dept. of Chemistry & Biochemistry', photoName: 'Allen_Taylor' },
    ],
  },
];

export const bulkServices = [
  {
    id: 0,
    name: 'Whole Exome Sequencing',
    description: 'A capture-based assay to assess the entire exome.',
    startingMaterial: 'DNA or DMP Library',
    libraryChemistry: 'KAPA Hyper',
    captureChemistry: 'xGen v2.0 from IDT (human) SinglePlex Mouse Exome from Twist (mouse)',
    sequencingReadLength: 'PE100',
    sequencingCoverage: 'Varies (see below)',
    deliverable: 'FASTQ; Pipeline analysis options available from CMO or BIC with additional charges',
    tableHeaders: ['sampleCoverage', 'sampleCost'],
    table: [
      { sampleCoverage: 30, sampleCost: 458 },
      { sampleCoverage: 70, sampleCost: 580 },
      { sampleCoverage: 100, sampleCost: 668 },
      { sampleCoverage: 150, sampleCost: 808 },
      { sampleCoverage: 200, sampleCost: 966 },
      { sampleCoverage: 250, sampleCost: 1106 },
    ],
  },
  {
    id: 1,
    name: 'Targeted Sequencing',
    description: 'Capture-based assays to assess specific genes within the exome.',
    startingMaterial: 'DNA or DMP Library',
    libraryChemistry: 'KAPA Hyper',
    captureChemistry: 'Custom probes from IDT',
    sequencingReadLength: 'PE100',
    sequencingCoverage: '500X T/250X N (IMPACT/HemePACT); 1000X (ACCESS)',
    deliverable: 'cBioPortal instance (IMPACT & HemePACT), pipeline analysis (ACCESS & M-IMPACT)',
    tableHeaders: ['panel', 'sampleType', 'sampleCost'],
    table: [
      { panel: 'IMPACT', sampleType: 'Tumor', sampleCost: 500 },
      { panel: 'IMPACT', sampleType: 'Normal', sampleCost: 250 },
      { panel: 'Mouse IMPACT', sampleType: '', sampleCost: 419 },
      { panel: 'HemePACT', sampleType: 'Tumor', sampleCost: 573 },
      { panel: 'HemePACT', sampleType: 'Normal', sampleCost: 350 },
      { panel: 'ACCESS', sampleType: 'Tumor', sampleCost: 600 },
      { panel: 'ACCESS', sampleType: 'Normal', sampleCost: 300 },
    ],
  },
  {
    id: 2,
    name: 'Transcriptome Sequencing',
    description: 'Techniques to enrich RNA and assess expressed transcripts',
    startingMaterial: 'RNA or cells (SMARTer only)',
    libraryChemistry: 'TruSeq stranded mRNA (polyA), TruSeq stranded total (Ribodepletion), SMART-Seq v4 + KAPA Hyper (SMARTer)',
    sequencingReadLength: 'PE100',
    sequencingCoverage: '20-100M',
    deliverable: 'FASTQ; analysis options from BIC',
    tableHeaders: ['libraryType', 'readNumber', 'sampleCost'],
    table: [
      { libraryType: 'PolyA', readNumber: '20-30', sampleCost: 300 },
      { libraryType: 'PolyA', readNumber: '30-40', sampleCost: 350 },
      { libraryType: 'PolyA', readNumber: '40-50', sampleCost: 400 },
      { libraryType: 'PolyA', readNumber: '50-60', sampleCost: 450 },
      { libraryType: 'PolyA', readNumber: '60-80', sampleCost: 575 },
      { libraryType: 'PolyA', readNumber: '80-100', sampleCost: 600 },
      { libraryType: 'RiboDepletion', readNumber: '20-30', sampleCost: 350 },
      { libraryType: 'RiboDepletion', readNumber: '30-40', sampleCost: 400 },
      { libraryType: 'RiboDepletion', readNumber: '40-50', sampleCost: 450 },
      { libraryType: 'RiboDepletion', readNumber: '50-60', sampleCost: 500 },
      { libraryType: 'RiboDepletion', readNumber: '60-80', sampleCost: 600 },
      { libraryType: 'RiboDepletion', readNumber: '80-100', sampleCost: 700 },
      { libraryType: 'SMARTer', readNumber: '20-30', sampleCost: 390 },
      { libraryType: 'SMARTer', readNumber: '30-40', sampleCost: 440 },
      { libraryType: 'SMARTer', readNumber: '40-50', sampleCost: 490 },
      { libraryType: 'SMARTer', readNumber: '50-60', sampleCost: 540 },
      { libraryType: 'SMARTer', readNumber: '60-80', sampleCost: 665 },
      { libraryType: 'SMARTer', readNumber: '80-100', sampleCost: 690 },
    ],
  },
  {
    id: 3,
    name: 'Whole Genome Sequencing',
    description: 'Assess the entire genome using PCR-free methods or minimal PCR cycles.',
    startingMaterial: 'DNA',
    libraryChemistry: 'KAPA Hyper',
    sequencingReadLength: 'PE150',
    sequencingCoverage: 'Varies; see below',
    deliverable: 'FASTQ',
    tableHeaders: ['sampleCoverage', 'sampleCostFrozen', 'sampleCostFfpe'],
    table: [
      { sampleCoverage: 30, sampleCostFrozen: 1067, sampleCostFfpe: 1263 },
      { sampleCoverage: 40, sampleCostFrozen: 1324, sampleCostFfpe: 1655 },
      { sampleCoverage: 50, sampleCostFrozen: 1557, sampleCostFfpe: 2046 },
      { sampleCoverage: 60, sampleCostFrozen: 1769, sampleCostFfpe: 2437 },
      { sampleCoverage: 80, sampleCostFrozen: 2229, sampleCostFfpe: 3219 },
      { sampleCoverage: 100, sampleCostFrozen: 3017, sampleCostFfpe: 4002 },
      { sampleCoverage: 150, sampleCostFrozen: 4009, sampleCostFfpe: 5957 },
    ],
  },
  {
    id: 4,
    name: 'Epigenome Sequencing',
    description: 'Various methods to assess the epigenetic structure of the genome',
    startingMaterial: 'Cells - no more than 24 samples/batch (ATAC), Transposed DNA (ChIP), DNA – samples in multiples of 4 (EPIC)',
    libraryChemistry: 'Nextera XT (ATAC), KAPA HTP (ChIP), TruSeq Methyl Capture (EPIC)',
    sequencingReadLength: 'PE100',
    sequencingCoverage: '40-50M (ATAC), 30-40M (ChIP), 40M (EPIC)',
    deliverable: 'FASTQ',
    tableHeaders: ['platform', 'sampleCost'],
    table: [
      { platform: 'ATAC-Seq', sampleCost: 450 },
      { platform: 'ChIP-Seq', sampleCost: 300 },
      { platform: 'EPIC Methyl Capture-Seq', sampleCost: 550 },
    ],
  },
  {
    id: 5,
    name: 'TCR Sequencing',
    description: 'Methods to enrich T-cell receptor sequences',
    startingMaterial: 'DNA - 12 sample minimum (Adaptive), RNA - 7 sample minimum (Archer), Cells (10X Genomics)',
    deliverable: 'Pipeline output (Adaptive & Archer)',
    tableHeaders: ['platform', 'sampleCost'],
    table: [
      { platform: 'Adaptive immunoSEQ (survey)', sampleCost: 350 },
      { platform: 'Adaptive immunoSEQ (deep)', sampleCost: 850 },
      { platform: 'Archer immunoverse', sampleCost: 494 },
      { platform: '10X Genomics V(D)J Enrichment', sampleCost: 2279 },
    ],
  },
  {
    id: 6,
    name: 'Other Services',
    description: 'Please email us if your sequencing needs do not fit in one of these categories.',
    tableHeaders: ['platform', 'sequencingDetails', 'deliverable', 'cost'],
    table: [
      { platform: 'Shallow/bacterial WGS', sequencingDetails: 'PE100, 10M reads', deliverable: 'FASTQ + CNV analysis', cost: '$182' },
      { platform: 'Amplicon Sequencing', sequencingDetails: 'Varies', deliverable: 'FASTQ', cost: 'please inquire' },
      {
        platform: 'CRISPR Cut Site Sequencing',
        sequencingDetails: '75K reads',
        deliverable: 'FASTQ + CRISPRESSO analysis',
        cost: '$70',
      },
      {
        platform: 'Archer FusionPlex',
        sequencingDetails: 'Solid Tumor Panel',
        deliverable: 'Archer portal access',
        cost: '$820',
      },
      {
        platform: 'Archer FusionPlex',
        sequencingDetails: 'Heme Panel',
        deliverable: 'Archer portal access',
        cost: '$610',
      },
    ],
  },
];

export const singleServices = [
  {
    id: 0,
    name: '10x Genomics Single Cell',
    description: 'Single-cell platforms to interrogate gene expression, immune repertoire, and/or protein expression.',
    startingMaterial: 'Single cell or nuclei suspension',
    libraryChemistry: 'Chromium Single Cell',
    sequencingReadLength: 'PE28/91',
    sequencingCoverage: '20K reads/cell (GEX), 5K reads/cell (V(D)J & cell hashing)',
    deliverable: 'FASTQ, Cell Ranger output',
    tableHeaders: ['xGenomicsPlatform', 'sampleCostLibrary', 'cellCostSequencing'],
    table: [
      { xGenomicsPlatform: '5′ OR 3′ Gene Expression', sampleCostLibrary: 2068, cellCostSequencing: '$0.05' },
      { xGenomicsPlatform: '5′ Gene Expression + V(D)J Enrichment', sampleCostLibrary: 2279, cellCostSequencing: '$0.06' },
      { xGenomicsPlatform: 'Feature Barcoding/Cell Hash Add-on', sampleCostLibrary: 116, cellCostSequencing: '$0.01' },
    ],
  },
  {
    id: 1,
    name: '10x Genomics Multiome',
    description: 'Single-cell ATAC-Seq + RNA-Seq from the same nucleus.',
    startingMaterial: 'Single nuclei suspension',
    libraryChemistry: 'Chromium Single Cell',
    sequencingReadLength: 'PE 28/90 (GEX), PE50 (ATAC)',
    sequencingCoverage: '20K reads/cell (GEX), 25K reads/cell (ATAC)',
    deliverable: 'FASTQ, Cell Ranger output',
    libraryCost: '$3,000/sample',
    sequencingCost: '$0.10/nucleus',
  },
  {
    id: 2,
    name: '10x Genomics Visium',
    description: 'Transcriptome sequencing of 1-10 cells along with spatial information.',
    startingMaterial: 'Fresh tissue',
    libraryChemistry: 'Visium Spatial Gene Expression',
    sequencingReadLength: 'PE28/90',
    sequencingCoverage: '50K reads/1-10 cells',
    deliverable: 'FASTQ, SpaceRanger output',
    tissueOptimizationCost: '$900 (once/tissue)',
    libraryCost: '$4,400/slide',
    sequencingCost: '$5,232 x %Area of squares covered',
  },
  {
    id: 3,
    name: 'Mission Bio Tapestri',
    description: 'A targeted single-cell platform to detect SNVs and CNVs in off-the-shelf or custom panels.',
    startingMaterial: 'Single cell or nuclei suspension',
    sequencingReadLength: 'PE150',
    sequencingCoverage: 'Panel dependent',
    deliverable: 'FASTQ + Tapestri Platform output',
    cost: '$2,800/sample',
  },
  {
    id: 4,
    name: 'PlateSeq',
    description:
      'A single- or low-cell Smart-seq 2 method to accommodate projects without enough cells for 10X Genomics, or users interested in capturing the entire body of the gene.',
    startingMaterial: 'Sorted cells',
    libraryChemistry: 'SMART-Seq + Nextera XT',
    sequencingReadLength: 'PE50',
    sequencingCoverage: '5M reads/cell',
    deliverable: 'FASTQ',
    libraryCost: '$1,680/plate',
    sequencingCost: '$17.50/cell',
  },
  {
    id: 5,
    name: 'DLP',
    description: 'A method to detect CNV in single cells.',
    startingMaterial: 'Single cell suspension',
    libraryChemistry: 'Custom protocol',
    sequencingReadLength: 'PE150',
    sequencingCoverage: '1M reads/cell',
    deliverable: 'FASTQ',
    libraryCost: '$2,300/up to 800 cells',
    sequencingCost: '$7/cell',
  },
];

export const otherServices = [
  {
    id: 0,
    name: 'Digital PCR',
    description:
      'PCR-based services for mutation detection, fusion detection, viral detection, or CNV. Hundreds of assays have been validated commercially or in house, but if your gene of interest is not on the list, IGO offers design & optimization services.',
    startingMaterial: 'DNA, RNA, Library',
    deliverable: 'Report',
    tableHeaders: ['service', 'cost'],
    table: [
      { service: 'New Assay Design & Optimization', cost: 200 },
      { service: 'New Assay Order (CNV)', cost: 200 },
      { service: 'New Assay Order (mutation)', cost: 375 },
      { service: 'Digital PCR (per reaction)', cost: 9.5 },
    ],
  },
  {
    id: 1,
    name: 'Cell Line Authentication',
    description: 'STR-based analysis to verify the identity of cell lines grown in vitro.',
    startingMaterial: 'DNA',
    kitChemistry: 'AmpFLSTR Identifiler (human), Custom (mouse; pending)',
    deliverable: 'Genotype + Database matching report',
    tableHeaders: ['species', 'cost'],
    table: [
      { species: 'Human', cost: 36 },
      { species: 'Mouse (coming soon)', cost: 44 },
    ],
  },
  {
    id: 2,
    name: 'Tissue and Bulk Extraction',
    description: 'Manual and automated methods for purifying RNA, DNA, or both from a variety of starting materials and sample types.',
    startingMaterial: 'See below. Other? Contact us.',
    deliverable: 'Nucleic acid + QC report',
    tableHeaders: ['startingMaterial', 'extractionOutput', 'sampleCost'],
    table: [
      { startingMaterial: 'Fresh frozen or OCT tissue/cells', extractionOutput: 'DNA', sampleCost: 25 },
      { startingMaterial: 'Viably frozen cells', extractionOutput: 'DNA', sampleCost: 40 },
      { startingMaterial: 'Blood', extractionOutput: 'DNA', sampleCost: 30 },
      { startingMaterial: 'FFPE tissue', extractionOutput: 'DNA', sampleCost: 35 },
      { startingMaterial: 'Fingernails', extractionOutput: 'DNA', sampleCost: 40 },
      { startingMaterial: 'Frozen tissue/cells (TRIzol, OCT, RLT, pellet)', extractionOutput: 'RNA', sampleCost: 33 },
      { startingMaterial: 'Viably frozen cells', extractionOutput: 'RNA', sampleCost: 48 },
      { startingMaterial: 'Frozen tissue/cells + COVID19 testing', extractionOutput: 'RNA', sampleCost: 93 },
      { startingMaterial: 'FFPE tissue', extractionOutput: 'RNA', sampleCost: 39 },
      { startingMaterial: 'All materials', extractionOutput: 'DNA + RNA (simultaneous extraction)', sampleCost: 55 },
      { startingMaterial: 'Special processing', extractionOutput: 'DNA/RNA', sampleCost: 15 },
    ],
  },
  // {
  //   id: 3,
  //   name: 'Investigator Prepared Libraries',
  //   description: 'Illumina sequencing of user-prepared libraries.',
  //   startingMaterial: 'DNA libraries',
  //   sequencingReadLength: 'Varies (see below); contact us for additional options',
  //   sequencingCoverage: 'Varies (see below); contact us for additional options',
  //   deliverable: 'FASTQ',
  //   tableHeaders: ['totalReads', 'pe50', 'pe100', 'pe150', 'special28'],
  //   // table: [
  //   //   { totalReads: '120M', pe50: 1092, pe100: 1746, pe150: 1746, special28: 1092 },
  //   //   { totalReads: '350M', pe50: 1414, pe100: 2035, pe150: 2820, special28: 2035 },
  //   //   { totalReads: '350M Rush', pe50: 3287, pe100: 4623, pe150: 5467, special28: 4623 },
  //   //   { totalReads: '1800M', pe50: 4881, pe100: 6613, pe150: 7727, special28: 6613 },
  //   // ],
  // },
  {
    id: 3,
    name: 'General Services',
    description: 'Other services offered by IGO.',
    tableHeaders: ['serviceType', 'serviceSubType', 'price'],
    table: [
      { serviceType: 'QC Service', serviceSubType: 'BioAnalyzer or TapeStation QC', price: '$11/sample' },
      { serviceType: 'QC Service', serviceSubType: 'Qubit/Quant-it', price: '$7/sample' },
      { serviceType: 'QC Service', serviceSubType: '%Human for PDX', price: '$19/sample' },
      { serviceType: 'Pathology Service', serviceSubType: 'Sectioning (curls)', price: '$15/block' },
      { serviceType: 'Pathology Service', serviceSubType: 'Sectioning (slides)', price: '$3.50/sample' },
      { serviceType: 'Pathology Service', serviceSubType: 'H&E Staining', price: '$7/sample' },
      { serviceType: 'Pathology Service', serviceSubType: 'Slide scraping', price: '$10/sample' },
      { serviceType: 'Pathology Service', serviceSubType: 'Macrodissection', price: '$3/slide' },
    ],
  },
];

export const customBlockPrices = [
  { readsBlock: 100, '100Cycles': '', '200Cycles': 900, '300Cycles': 1500 },
  { readsBlock: 400, '100Cycles': '$900', '200Cycles': 1000, '300Cycles': 1100 },
  { readsBlock: 800, '100Cycles': '$1800', '200Cycles': 1990, '300Cycles': 2150 },
  { readsBlock: 1800, '100Cycles': '$4032', '200Cycles': 4464, '300Cycles': 4842 },
  { readsBlock: 2750, '100Cycles': '$6160', '200Cycles': 6820, '300Cycles': 7398 },
  { readsBlock: 3600, '100Cycles': '$8064', '200Cycles': 8928, '300Cycles': 9684 },
  { readsBlock: 11000, '100Cycles': '', '200Cycles': 14300, '300Cycles': 16000 },
];

export const archerFusionGenes = [
  ['ACVR2A', 'AKT1', 'ALK', 'AR', 'ARAF'],
  ['ARHGAP26', 'BCOR', 'BCORL1', 'BRAF', 'BRD4'],
  ['CAMTA1', 'CCNB3', 'CIC', 'CSF1', 'DNAJB1'],
  ['EGFR', 'EPC1', 'ERBB2', 'ERBB3', 'ERBB4'],
  ['ERG', 'ESR1', 'ETV1', 'ETV4', 'ETV5'],
  ['ETV6', 'EWSR1', 'FGF1', 'FGFR1', 'FGFR2'],
  ['FGFR3', 'FGFR4', 'FGR', 'FLT1', 'FLT3'],
  ['FOS', 'FOSB', 'FOXO1', 'FOXR2', 'FUS'],
  ['NCOA1', 'NCOA2', 'NCOA3', 'NFATC2', 'NFE2L2'],
  ['NOTCH1', 'NOTCH2', 'NR4A3', 'NRG1', 'NTRK1'],
  ['NTRK2', 'NTRK3', 'NUTM1', 'NUTM2A', 'NUTM2B'],
  ['PAX3', 'PAX5', 'PAX7', 'PDGFB', 'PDGFD'],
  ['PDGFRA', 'PDGFRB', 'PGR', 'PHF1', 'PIK3CA'],
  ['PLAG1', 'PPARG', 'PRB3', 'PRKACA', 'PRKACB'],
  ['PRKCA', 'PRKCB', 'PRKD1', 'PRKD2', 'PRKD3'],
  ['PTCH1', 'PTPN1', 'RAD51B', 'RAF1', 'RELA'],
  ['RET', 'RLF', 'ROS1', 'RSPO2', 'RSPO3'],
  ['SRF', 'SS18', 'SS18L1', 'STAT6', 'TAF15'],
  ['TCF12', 'TERT', 'TFE3', 'TFEB', 'TFG'],
  ['THADA', 'TMPRSS2', 'USP6', 'VGLL2', 'VGLL3'],
  ['WWTR1', 'YAP1', 'YWHAE'],
];

export const tutorials = [
  {
    slug: 'ilabs_sample_sub',
    title: 'IGO’s iLab and Sample Submission Process',
    speakers: 'Marisa Dunigan and Lisa Wagner',
    date: 'May 5, 2020',
    screenshot: 'ilab_sample_submission',
  },
  // { slug: "cellranger", title: "Data Analysis with CellRanger", speakers: "Sarah Parsons from 10X Genomics", date: "May 7, 2020" },
  {
    slug: 'splunk_webinar',
    title: 'Splunk: a Data Visualization Tool used for Operational Insight',
    speakers: 'Anna Patruno',
    date: 'May 12, 2020',
    screenshot: 'splunk',
  },
  {
    slug: 'why_igo_says_no',
    title: 'Why IGO says ‘No!’',
    speakers: 'Liping Sun and Ruchi Patel',
    date: 'May 21, 2020',
    screenshot: 'igo_alternatives',
  },
  {
    slug: 'DRAGEN',
    title: 'DRAGEN platform: accurate, ultra-rapid secondary analysis of sequencing data',
    speakers: 'Rami Mehio from Illumina',
    date: 'May 28, 2020',
    screenshot: 'dragen',
  },
];

export const bookingDetails = [
  { application: '10x Genomics,', formPrompts: { name: null, email: null, sampleNumber: null, chemustry: null } },
];
